In [1]:
import json
import pandas as pd
import altair as alt
import os
import numpy as np

alt.data_transformers.enable("vegafusion")

DataTransformerRegistry.enable('vegafusion')

In [2]:
def register_alt_themes(color_schemes):
    for name, color_scheme, font_size_multiplier in color_schemes:
        
        @alt.theme.register(name, enable=False)
        def register_theme(c=color_scheme, f=font_size_multiplier) -> alt.theme.ThemeConfig:
            return {
                "config": {
                    "range": {
                        "category": c
                    },
                    "axis": {
                        "titleFontSize": 34 * f,
                        "labelFontSize": 32 * f, 
                        "limit": 0,
                    },
                    
                    "legend": {
                        "titleFontSize": 32 * f,
                        "labelFontSize": 30 * f,
                        "labelLimit": 0,
                        "titleLimit": 0,
                    },
                    "title": {
                        "fontSize": 34 * f,
                        "limit": 0,
                    },
                    "text": {
                        "fontSize": 32 * f, 
                        "limit": 0,
                        #"fontWeight": "bold",
                    },
                }
            }

color_scheme_1 = ["#1f77b4", "#ff7f0e", "#2ca02c", "#e45756", "#9467bd", "#8c564b", "#e377c2", "#7f7f7f", "#efb118", "#17becf", "#e41a1c"]
color_scheme_2 = ["#4269d0", "#efb118", "#ff725c", "#6cc5b0", "#3ca951", "#ff8ab7", "#a463f2", "#97bbf5", "#9c6b4e", "#9498a0", "#9498a0"]
color_scheme_many_categories = {"scheme": "category20"}

register_alt_themes([('theme_color_scheme_1', color_scheme_1, 1.0), 
                     ('theme_color_scheme_2', color_scheme_2, 1.0), 
                     ('theme_color_scheme_many_categories', color_scheme_many_categories,  1.0),
                     ('theme_color_scheme_2_larger_fontsize', color_scheme_2, 1.5)])

alt.theme.enable('theme_color_scheme_2')

ThemeRegistry.enable('theme_color_scheme_2')

In [3]:
query_categories = {
    # For SPARQL vs. SQL benchmark
    'samples_with_specific_elements': 'Research objects', 
    'samples_with_specific_elements_exclusive': 'Research objects', 
    'samples_with_substrates': 'Research objects', 
    'samples_not_composed_of_elements': 'Research objects', 
    'samples_and_authors': 'Research objects', 
    
    'query_user_details': 'Users', 
    'samples_per_user': 'Users', 
    
    'query_based_on_composition_values': 'Compositions', 
    'composition_count_per_MA': 'Compositions', 

    'measurement_to_handovers': 'Handovers', 
    'handovers_with_specific_measurement_type': 'Handovers', 

    'get_edx_csv_measurements': 'Measurements', 
    'measurements_and_authors': 'Measurements'
}

In [4]:
materialization_times = []
querying_times = []
materialization_and_querying_times = []
per_mapping_querying_times = []

cpu_usage_trace = []
memory_usage_trace = []

n_triples = []
postprocessing_times = []
postprocessing_times_total = []

cpu_usage_trace_postprocessing = []
memory_usage_trace_postprocessing = []

query_benchmark_results = []

conversion_times = []


perf_logs = [json.load(open('iswc_performance_test.json'))]
for perf_log in perf_logs:
    for test in perf_log:
        # Skip debugging tests
        if test["config"]["num_main_samples"] not in [299, 1000, 2000, 3000, 4000, 5000, 6000, 7000, 8000, 9000, 10000]:
            continue

        if test["config"]["n_run"] > 2: # The first 3 runs
            continue
        
        if test["config"]["multiplier"] == 1:
            multiplier = "Original activity"
        elif test["config"]["multiplier"] == 1.5:
            multiplier = "+50%"
        elif test["config"]["multiplier"] == 2:
            multiplier = "+100%"
        else:
            continue # Skip debugging tests
    
        n_triples.append({"n_samples": test["config"]["num_main_samples"], 
                          "multiplier": multiplier, 
                          "n_triples": test["n_triples_generated"]})
    
        # Query benchmark
        for query, (time_sql, time_sparql) in test["query_benchmark_results"].items():
            query_benchmark_results.append({"n_samples": test["config"]["num_main_samples"], 
                                            "multiplier": multiplier, 
                                            "query": query,
                                            "category": query_categories[query],
                                            "time": time_sql,
                                            "type": "sql"})
    
            query_benchmark_results.append({"n_samples": test["config"]["num_main_samples"], 
                                            "multiplier": multiplier, 
                                            "query": query,
                                            "category": query_categories[query],
                                            "time": time_sparql,
                                            "type": "sparql"})
        
        # Materialization times
        materialization_times.append({"n_samples": test["config"]["num_main_samples"],
                                      "multiplier": multiplier,
                                      "n_run": test["config"]["n_run"],
                                      "mat_time": test["mappings_performance_log"]["materialization_real_time"]})

        querying_times.append({"n_samples": test["config"]["num_main_samples"],
                               "multiplier": multiplier,
                               "n_run": test["config"]["n_run"],
                               "querying_time": test["mappings_performance_log"]["query_execution_real_time"]})

        materialization_and_querying_times.append({"n_samples": test["config"]["num_main_samples"],
                                                   "multiplier": multiplier,
                                                   "n_run": test["config"]["n_run"],
                                                   "mat_time": test["mappings_performance_log"]["materialization_real_time"] + test["mappings_performance_log"]["query_execution_real_time"]})


        # Per-mapping query times
        for mapping_path, t in test["mappings_performance_log"]["per_mapping_query_execution_times"]:
            category = os.path.basename(os.path.dirname(mapping_path)).replace("_", " ").capitalize()
            mapping_name = os.path.splitext(os.path.basename(mapping_path))[0].replace("_", " ")
            per_mapping_querying_times.append({"mapping_name": mapping_name,
                                               "category": category,
                                               "n_samples": test["config"]["num_main_samples"],
                                               "multiplier": multiplier,
                                               "n_run": test["config"]["n_run"],
                                               "query_time": t})
        # Postprocessing times
        postprocessing_time_sum = 0
        for postprocessing_step, postprocessing_time in test["postprocessing_performance_log"].items():    
            postprocessing_time_sum += postprocessing_time
            postprocessing_times.append({"step": postprocessing_step,
                                         "n_samples": test["config"]["num_main_samples"],
                                         "multiplier": multiplier, 
                                         "time": postprocessing_time})
        
        postprocessing_times_total.append({"n_samples": test["config"]["num_main_samples"],
                                         "multiplier": multiplier, 
                                         "time": postprocessing_time_sum,
                                         "n_run": test["config"]["n_run"]})
    
        # Materialization resource usage
        for i, (cpu_usage, memory_usage_dict) in enumerate(test["resource_usage_mappings"]):
            cpu_usage_trace.append({ 
                "time": i, # Each tick is a second
                "cpu_usage": cpu_usage,
                "n_samples": test["config"]["num_main_samples"],
                "multiplier": multiplier,
                "n_run": test["config"]["n_run"]
            })

            memory_usage_mappings = 0
            if "materialized_triples" in memory_usage_dict["used_mem_per_file"]:
                memory_usage_mappings = memory_usage_dict["used_mem_per_file"]["materialized_triples"]
            
            memory_usage_trace.append({ 
                "time": i, # Each tick is a second
                "memory_usage_sql": memory_usage_dict["sql_server"],
                "memory_usage_mappings": memory_usage_mappings,
                "n_samples": test["config"]["num_main_samples"],
                "multiplier": multiplier,
                "n_run": test["config"]["n_run"]
            })
    
        # Postprocessing resource usage
        for i, (cpu_usage, memory_usage) in enumerate(test["resource_usage_postprocessing"]):
            cpu_usage_trace_postprocessing.append({ 
                "time": i, # Each tick is a second
                "cpu_usage": cpu_usage,
                "n_samples": test["config"]["num_main_samples"],
                "multiplier": multiplier,
                "n_run": test["config"]["n_run"]
            })
    
            memory_usage_trace_postprocessing.append({ 
                "time": i, # Each tick is a second
                "memory_usage": memory_usage,
                "n_samples": test["config"]["num_main_samples"],
                "multiplier": multiplier,
                "n_run": test["config"]["n_run"]
            })
            
        yarrrml_to_rml_conversion_real_time = test["mappings_performance_log"]["yarrrml_to_rml_conversion_real_time"]

        conversion_times.append({"n_samples": test["config"]["num_main_samples"],
                                 "yarrrml_to_rml_conversion_real_time": yarrrml_to_rml_conversion_real_time,
                                 "multiplier": multiplier,
                                 "n_run": test["config"]["n_run"]})

materialization_times = pd.DataFrame(materialization_times)
querying_times = pd.DataFrame(querying_times)
materialization_and_querying_times = pd.DataFrame(materialization_and_querying_times)
conversion_times = pd.DataFrame(conversion_times)
per_mapping_querying_times = pd.DataFrame(per_mapping_querying_times)

cpu_usage_trace = pd.DataFrame(cpu_usage_trace)
memory_usage_trace = pd.DataFrame(memory_usage_trace)
n_triples = pd.DataFrame(n_triples)

postprocessing_times = pd.DataFrame(postprocessing_times)
postprocessing_times_total = pd.DataFrame(postprocessing_times_total)
cpu_usage_trace_postprocessing = pd.DataFrame(cpu_usage_trace_postprocessing)
memory_usage_trace_postprocessing = pd.DataFrame(memory_usage_trace_postprocessing)

query_benchmark_results = pd.DataFrame(query_benchmark_results)

# Simplify the categories for plots:
#    1) Reqs.for synthesis and ideas mappings are separated as they will be expanded in the future, but act as measurements right now
#    2) The relations between objects<->objects and object<->measurements are treated as measurements, as they conform the vast majority of them
#    3) Handovers and activities are separated for readability, but both belong to the handover workflows construction
#    4) Users are also in their own category, but their mappings amount to nothing - we can consider them as part of measurements
per_mapping_querying_times.loc[per_mapping_querying_times['category'] == 'Requests for synthesis', 'category'] = 'Measurements'
per_mapping_querying_times.loc[per_mapping_querying_times['category'] == 'Ideas', 'category'] = 'Measurements'
per_mapping_querying_times.loc[per_mapping_querying_times['category'] == 'Generic relations', 'category'] = 'Measurements'
per_mapping_querying_times.loc[per_mapping_querying_times['category'] == 'Users', 'category'] = 'Measurements'

per_mapping_querying_times.loc[per_mapping_querying_times['category'] == 'Samples', 'category'] = 'Research objects'

per_mapping_querying_times.loc[per_mapping_querying_times['category'] == 'Handovers', 'category'] = 'Handovers'
per_mapping_querying_times.loc[per_mapping_querying_times['category'] == 'Activities', 'category'] = 'Handovers'

# Number of triples per number of samples

In [5]:
base = alt.Chart(n_triples).encode(
    x=alt.X('n_samples', title="Number of materials libraries",axis=alt.Axis(
        values=list(range(0, n_triples['n_samples'].max() + 1000, 1000))
    )),
    y=alt.Y('mean(n_triples)', title="RDF triples generated", axis=alt.Axis(tickCount=10, format='.3s')),
    color=alt.Color(
        'multiplier',
        sort=['Original activity', '+25%', '+50%', '+75%', '+100%'],
        legend=alt.Legend(title="Increased activity modifier", orient="top")
    ),
    shape=alt.Shape('multiplier', legend=None),
    strokeDash=alt.StrokeDash('multiplier', legend=None)
)

line = base.mark_line(size=3)  # thicker line
points = base.mark_point(size=100)  # add points

text = base.mark_text(
    align='center',
    baseline='middle',
    dy=-20
).encode(
    text=alt.Text('mean(n_triples):Q', format='.3s')#,.0f')
)


error_bands = alt.Chart(n_triples).mark_errorband(extent='stdev').encode(
    x='n_samples:Q',
    y=alt.Y('n_triples:Q', title=''),# title='Average number of triples'),
    color=alt.Color(
        'multiplier:N',
        sort=['Original activity', '+25%', '+50%', '+75%', '+100%'],
        legend=None
    )
)


# + text
n_triples_plot = (line + points + error_bands).properties(
    width=900, # For the paper: 800
    height=800 # For the paper: 600
).configure(
    # The key setting to make the overall figure fit the specified size
    autosize='fit' 
)

n_triples_plot.save('n_triples.pdf')

In [6]:
with pd.option_context('display.float_format', '{:.3f}'.format):
    print(n_triples.groupby(['multiplier'])['n_triples'].mean().reset_index())

          multiplier     n_triples
0              +100% 116884587.788
1               +50%  47101418.091
2  Original activity  10021915.182

# Postprocessing time

In [7]:
chart = alt.Chart(postprocessing_times_total).mark_line().encode(
    x=alt.X('n_samples:Q', title="Number of materials libraries", axis=alt.Axis(
        values=list(range(0, materialization_times['n_samples'].max() + 1000, 1000))
    )),
    # Note: Avg across runs, sum over all postprocessing steps for each x tick and multiplier
    y=alt.Y('mean(time):Q', title="Postprocessing time (seconds)"),
    color=alt.Color(
        'multiplier',
        sort=['Original activity', '+25%', '+50%', '+75%', '+100%'], 
        legend=alt.Legend(
            title="Increased activity modifier",
            orient="top"
        )
    ),
    shape=alt.Shape('multiplier', legend=None),
    strokeDash=alt.StrokeDash('multiplier', legend=None)
).properties(
    width=800, # For the paper: 800
    height=600  # For the paper: 600
)

line = chart.mark_line(size=3) 
points = chart.mark_point(size=100) 

text = chart.mark_text(
    align='center',
    baseline='middle',
    dx=0,
    dy=-20
).encode(
    text=alt.Text('mean(time):Q', format=".1f")
)

error_bands = alt.Chart(postprocessing_times_total).mark_errorband(extent='stdev').encode(
    x='n_samples:Q',
    y=alt.Y('mean(time):Q', title='Postprocessing time (seconds)'),
    color=alt.Color(
        'multiplier:N',
        sort=['Original activity', '+25%', '+50%', '+75%', '+100%'],
        legend=None
    )
)

postprocessing_plot = (chart + line + points + error_bands) # + text


postprocessing_plot.save('total_postprocessing_time_per_n_samples.pdf')

## Percentage of postprocessing time on top of materialization (avg)

In [8]:
materialization_times

    n_samples         multiplier  n_run    mat_time
0         299  Original activity      0    5.860775
1        1000  Original activity      0    9.645658
2        2000  Original activity      0   15.588121
3        3000  Original activity      0   21.075831
4        4000  Original activity      0   25.957881
..        ...                ...    ...         ...
94       6000              +100%      2  535.864753
95       7000              +100%      2  616.249779
96       8000              +100%      2  729.276017
97       9000              +100%      2  810.650739
98      10000              +100%      2  889.286119

[99 rows x 4 columns]

In [9]:
postprocessing_times_total["mat_time"] = materialization_times["mat_time"]

In [10]:
postprocessing_times_total = postprocessing_times_total.groupby(['n_samples', 'multiplier'])[['time', 'mat_time']].mean().reset_index()

In [11]:
postprocessing_times_total = postprocessing_times_total.groupby('multiplier')['time'].mean()
postprocessing_times_total

multiplier
+100%                373.080589
+50%                 163.605859
Original activity     43.523753
Name: time, dtype: float64

# Postprocessing CPU usage

In [12]:
charts = [  
    alt.Chart(cpu_usage_trace_postprocessing.query("multiplier == @m")).mark_line().encode(
        x=alt.X('time:N', title="Elapsed time (seconds)", axis=alt.Axis(labelAngle=0)),
        y=alt.Y('mean(cpu_usage):Q', title="Total CPU usage (Avg. across repetitions)"),
        color=alt.Color(
            'n_samples:N',
            legend=alt.Legend(
                title="Number of materials libraries",
                orient="top"
            )
        ),
        shape=alt.Shape('n_samples:N', legend=None),
        strokeDash=alt.StrokeDash('n_samples:N', legend=None)
    ).properties(title=f"Multiplier: {m}", width=1920, height=1080)
    for m in ['Original activity', '+50%', '+100%']
]

top = alt.hconcat(*charts[:3], spacing=20)
bottom = alt.hconcat(
    alt.Chart().mark_text(text='').properties(width=125), 
    *charts[3:],
    alt.Chart().mark_text(text='').properties(width=125)   
)


title = alt.TitleParams(
    text="Postprocessing CPU usage (% of total use over 24c/48t) (Avg. across all tests)",
    offset=100,
    anchor='middle',
    fontSize=64
)
chart = alt.vconcat(top, bottom, spacing=40, title=title)


chart.save('postprocessing_cpu_usage.pdf')

# Postprocessing memory usage

In [13]:
memory_usage_trace_postprocessing['memory_usage_gib'] = memory_usage_trace_postprocessing['memory_usage'] / (1024**3)

In [14]:
charts = [  
    alt.Chart(memory_usage_trace_postprocessing.query("multiplier == @m")).mark_line().encode(
        x=alt.X('time:Q', title="Elapsed time (seconds)", axis=alt.Axis(labelAngle=0, tickCount=10)),
        y=alt.Y('mean(memory_usage_gib)', 
                title="Memory usage (GiB) (Avg. across repetitions)", 
                axis=alt.Axis(format=".1f", tickCount=5),
                scale=alt.Scale(zero=False)),
        color=alt.Color(
            'n_samples:N',
            legend=alt.Legend(
                title="Number of materials libraries",
                orient="top"
            )
        ),
        shape=alt.Shape('n_samples:N', legend=None),
        strokeDash=alt.StrokeDash('n_samples:N', legend=None)
    ).properties(title=f"Multiplier: {m}", width=1920, height=1080)
    for m in ['Original activity', '+50%', '+100%']
]

top = alt.hconcat(*charts[:3], spacing=20)
bottom = alt.hconcat(
    alt.Chart().mark_text(text='').properties(width=125),  
    *charts[3:],
    alt.Chart().mark_text(text='').properties(width=125)   
)

title = alt.TitleParams(
    text="Postprocessing memory usage (starting values indicate Virtuoso's initial reserved memory) (Avg. across all tests)",
    offset=100,
    anchor='middle',
    fontSize=64
)

chart = alt.vconcat(top, bottom, spacing=40, title=title)

chart.save('postprocessing_memory_usage.pdf')

# Total materialization time per number of samples

In [15]:
chart = alt.Chart(materialization_times).mark_line().encode(
    x=alt.X('n_samples', title="Number of materials libraries", axis=alt.Axis(
        values=list(range(0, materialization_times['n_samples'].max() + 1000, 1000))
    )),
    y=alt.Y('mean(mat_time)', title="Materialization time (w/o query execution) (seconds)"),
    color=alt.Color(
        'multiplier',
        sort=['Original activity', '+50%', '+100%'], 
        legend=alt.Legend(
            title="Multiplier value",
            orient="top"
        )
    ),
    shape=alt.Shape('multiplier', legend=None),
    strokeDash=alt.StrokeDash('multiplier', legend=None)
).properties(
    width=1920, # For the paper: 800
    height=1080 # For the paper: 600
)

line = chart.mark_line(size=3)
points = chart.mark_point(size=100)

text_1 = chart.mark_text(
    align='center',
    baseline='middle',
    dx=0,
    dy=-20
).encode(
    text=alt.condition(
        alt.datum.multiplier != "Original activity",
        alt.Text('mean(mat_time):Q', format=",.1f"),
        alt.value('')
    )
)

text_2 = chart.mark_text(
    align='center',
    baseline='middle',
    dx=0,
    dy=-20
).encode(
    text=alt.condition(
        alt.datum.multiplier == "Original activity",
        alt.Text('mean(mat_time):Q', format=",.1f"),
        alt.value('')
    )
)

error_bands = alt.Chart(materialization_times).mark_errorband(extent='stdev').encode(
    x='n_samples:Q',
    y=alt.Y('mat_time:Q', title='Materialization time (w/o query execution) (seconds)'),
    color=alt.Color(
        'multiplier:N',
        sort=['Original activity', '+50%', '+100%'],
        legend=None
    )
)

chart = (chart + line + points + text_1 + text_2 + error_bands)

chart.save('materialization_time_per_n_samples.pdf')

# Avg. YARRRML -> RML conversion time

This is just to see that the overhead of the Docker containers for the YARRRML conversion is hurting us. Since this can be done
in an offline manner after modifying the mappings, we exclude it and use the maximum materialization time instead.

In [16]:
conversion_times

    n_samples  yarrrml_to_rml_conversion_real_time         multiplier  n_run
0         299                             0.438483  Original activity      0
1        1000                             0.394111  Original activity      0
2        2000                             0.406055  Original activity      0
3        3000                             0.479803  Original activity      0
4        4000                             0.390370  Original activity      0
..        ...                                  ...                ...    ...
94       6000                             0.680629              +100%      2
95       7000                             0.701787              +100%      2
96       8000                             0.722500              +100%      2
97       9000                             0.663805              +100%      2
98      10000                             1.282521              +100%      2

[99 rows x 4 columns]

In [17]:
chart = alt.Chart(conversion_times).mark_line().encode(
    x=alt.X('n_samples', title="Number of materials libraries"),
    y=alt.Y('mean(yarrrml_to_rml_conversion_real_time)', title="YARRRML -> RML conversion time (seconds)",
            axis=alt.Axis(format=".1f")),
).properties(
    width=1920, height=1080 # For the paper: 800 x 600
)

line = chart.mark_line(size=3)
points = chart.mark_point(size=100)

text_1 = chart.mark_text(
    align='left',
    baseline='middle',
    dx=5,
    dy=10
).encode(
    text=alt.condition(
        alt.datum.multiplier != "No multiplier",
        alt.Text('mean(yarrrml_to_rml_conversion_real_time):Q', format=".1f"),
        alt.value('')
    )
)

text_2 = chart.mark_text(
    align='left',
    baseline='middle',
    dx=5,
    dy=20
).encode(
    text=alt.condition(
        alt.datum.multiplier == "No multiplier",
        alt.Text('mean(yarrrml_to_rml_conversion_real_time):Q', format=".1f"),
        alt.value('')
    )
)

error_bands = alt.Chart(conversion_times).mark_errorband(extent='stdev').encode(
    x='n_samples:Q',
    y=alt.Y('mean(yarrrml_to_rml_conversion_real_time):Q', title='YARRRML -> RML conversion time (seconds)'),
)

chart = (chart + line + points + text_1 + text_2 + error_bands)

chart.save('avg_yarrrml_conversion_time.pdf')

# Main materialization times plot

## Total materialization time per number of samples (in multiple plots)

In [18]:
real_mat_times_charts = []

indexes_with_y_axis = [0]

for i, m in enumerate(['Original activity', '+50%', '+100%']):
    if i in indexes_with_y_axis:
        chart_y_axis = alt.Y('mean_val:Q', title="Total materialization time (seconds)", 
                             axis=alt.Axis(tickCount=10), 
                             scale=alt.Scale(type='log', base=2))
        # Move the title up or down depending on the plot. I could not find another way...
        title_dy = 0
    else:
        chart_y_axis = alt.Y('mean_val:Q', title="Total materialization time (seconds)", 
                             axis=alt.Axis(labels=False, title=None, ticks=False, domain=False, tickCount=10), 
                             scale=alt.Scale(type='log', base=2))
        title_dy = -15
    
    # X-axis title only for the middle chart
    x_title = "Number of materials libraries" if i == 1 else None
    
    base = alt.Chart(materialization_and_querying_times.query("multiplier == @m")).transform_calculate(
        log_val='log(datum.mat_time)/log(2)'
    ).transform_aggregate(
        mean_log='mean(log_val)',
        sd_log='stdev(log_val)',
        mean_val='mean(mat_time)',
        groupby=['n_samples']
    ).transform_calculate(
        upper='pow(2, datum.mean_log + datum.sd_log)',
        lower='pow(2, datum.mean_log - datum.sd_log)'
    ).encode(
        x=alt.X('n_samples:Q', title=x_title, axis=alt.Axis(
            values=list(range(0, materialization_and_querying_times['n_samples'].max() + 1000, 1000)),
            labelAngle=-45
        ))
    ).properties(
        title=alt.TitleParams(
            text=f"Increased activity modifier: {m}" if i > 0 else "Original activity",
            dy=title_dy
        ),
        width=625, 
        height=550
    )
    
    error_bars = base.mark_rule(color='#001F3F', size=2).encode(
        y=alt.Y('lower:Q'),
        y2='upper:Q'
    )

    error_caps = base.mark_tick(color='#001F3F', thickness=2, size=10).encode(
        y=alt.Y('lower:Q'),
        y2='upper:Q'
    )
    
    line_layer = base.mark_line(size=3, color='black').encode(
        y=chart_y_axis
    )
    
    point_layer = base.mark_point(size=100, filled=True, color='#001F3F').encode(
        y=chart_y_axis
    )

    # Combine with rule and ticks instead of area
    final_chart = error_bars + error_caps + line_layer + point_layer
    real_mat_times_charts.append(final_chart)

real_mat_times_chart = alt.hconcat(*real_mat_times_charts, spacing=20).resolve_scale(
    y='shared'
)

## Per-mapping category query times

In [19]:
per_mapping_times_w_sums = (
    # Across mapping names
    per_mapping_querying_times.groupby(['category', 'n_samples', 'multiplier', 'n_run'], as_index=False) # Per run
      .agg(
          # Not representative, as all mappings are run in parallel
          #real_time_sum_for_category=('query_time', 'sum'), 
          
          # This corresponds to the maximum time for the mapping of each category, i.e.
          # the time for the last parallel job to finish for that category - hence, this
          # is the *real* time for the category
          real_time_max_for_category=('query_time', 'max'),

          real_time_std_for_category=('query_time', 'std') 
      )
)

In [20]:
per_mapping_times_w_sums_2 = (
    # Across mapping names
    per_mapping_querying_times.groupby(['category', 'n_samples', 'multiplier'], as_index=False) # Per run
      .agg(
          # Not representative, as all mappings are run in parallel
          #real_time_sum_for_category=('query_time', 'sum'), 
          
          # This corresponds to the maximum time for the mapping of each category, i.e.
          # the time for the last parallel job to finish for that category - hence, this
          # is the *real* time for the category
          real_time_max_for_category=('query_time', 'max'),

          real_time_std_for_category=('query_time', 'std') 
      )
)

In [21]:
mat_times_per_cat_charts = []

x_axis_values = list(range(0, per_mapping_times_w_sums['n_samples'].max() + 1000, 1000))

indexes_with_y_axis = [0] 

for i, m in enumerate(['Original activity', '+50%', '+100%']):
    if i in indexes_with_y_axis:
        bar_y_axis = alt.Y('mean(real_time_max_for_category):Q', 
                           title="SQL querying time (seconds)", 
                           axis=alt.Axis(tickCount=10), 
                           scale=alt.Scale(type='log', base=2))
        # Move the title up or down depending on the plot. I could not find another way...
        title_dy = 0
    else:
        y_axis_config = alt.Axis(labels=False, title=None, ticks=False, domain=False, tickCount=10)
        bar_y_axis = alt.Y('mean(real_time_max_for_category):Q', 
                           axis=y_axis_config, 
                           scale=alt.Scale(type='log', base=2))
        title_dy = -15

    # X-axis title only for the middle chart
    x_title = "Number of materials libraries" if i == 1 else None
    
    base_layer = alt.Chart(per_mapping_times_w_sums.query("multiplier == @m")).encode(
        x=alt.X('n_samples:Q', 
                title=x_title,
                axis=alt.Axis(values=x_axis_values, labelAngle=-45)),
        y=bar_y_axis,
        color=alt.Color('category:N', 
                        legend=alt.Legend(title="Mapping category", orient="bottom"))
    )

    line_layer = base_layer.mark_line(size=3)
    point_layer = base_layer.mark_point(size=100, filled=True)

    error_chart = alt.Chart(per_mapping_times_w_sums.query("multiplier == @m")).transform_calculate(
        log_val='log(datum.real_time_max_for_category)/log(2)'
    ).transform_aggregate(
        mean_log='mean(log_val)',
        sd_log='stdev(log_val)',
        groupby=['category', 'n_samples']
    ).transform_calculate(
        upper_log='datum.mean_log + datum.sd_log',
        lower_log='datum.mean_log - datum.sd_log',
        upper='pow(2, datum.upper_log)',
        lower='pow(2, datum.lower_log)'
    ).mark_rule().encode(
        x=alt.X('n_samples:Q'),
        y=alt.Y('lower:Q', scale=alt.Scale(type='log', base=2)),
        y2='upper:Q',
        color=alt.Color('category:N', legend=None)
    )
    
    combined = (line_layer + point_layer + error_chart).properties(
        title=alt.TitleParams(
            text=f"Increased activity modifier: {m}" if i > 0 else "Original activity",
            dy=title_dy
        ),
        width=625, 
        height=550
    )
    
    mat_times_per_cat_charts.append(combined)

mat_times_per_category_chart = alt.hconcat(*mat_times_per_cat_charts, spacing=20).resolve_scale(y='shared')

## Combination

In [22]:
#top = alt.hconcat(*real_mat_times_charts, spacing=15).resolve_scale(x='shared', y='shared', color='shared')
#bot = alt.hconcat(*mat_times_per_cat_charts, spacing=10).resolve_scale(x='shared', y='shared', color='shared')

#alt.vconcat(top, bot, spacing=50).save('materialization_time_per_category_and_n_samples_all_horizontal.pdf')

In [23]:
real_mat_times_chart.save('first_horizontal_plot.pdf')
mat_times_per_category_chart.save('second_horizontal_plot.pdf')

# Materialization CPU Usage

In [24]:
charts = [  
    alt.Chart(cpu_usage_trace.query("multiplier == @m")).mark_line().encode(
        x=alt.X('time:Q', title="Elapsed time (seconds)", axis=alt.Axis(labelAngle=0, tickCount=10)),
        y=alt.Y('mean(cpu_usage)', title="Total CPU usage (%)"),
        color=alt.Color(
            'n_samples:N',
            legend=alt.Legend(
                title="Number of materials libraries",
                orient="top"
            )
        ),
        shape=alt.Shape('multiplier', legend=None),
        strokeDash=alt.StrokeDash('multiplier', legend=None)
    ).properties(title=f"Multiplier: {m}", width=1920, height=1080)
    for m in ['Original activity', '+50%', '+100%']
]

top = alt.hconcat(*charts[:3], spacing=20)
bottom = alt.hconcat(
    alt.Chart().mark_text(text='').properties(width=125),
    *charts[3:],
    alt.Chart().mark_text(text='').properties(width=125) 
)

title = alt.TitleParams(
    text="Materialization CPU usage (% of total use over 24c/48t) (SQL database + RMLMapper and RMLStreamer mapping jobs) (Avg. across all tests)",
    offset=100,
    anchor='middle',
    fontSize=64
)
chart = alt.vconcat(top, bottom, spacing=40, title=title)

chart.save('materialization_cpu_usage.pdf')

# Materialization memory usage

In [25]:
memory_usage_trace['mermoy_usage_total'] = memory_usage_trace['memory_usage_sql'] + memory_usage_trace['memory_usage_mappings']

In [26]:
memory_usage_trace['memory_usage_gib'] = memory_usage_trace['mermoy_usage_total'] / (1024**3)

In [27]:
charts = [  
    alt.Chart(memory_usage_trace.query("multiplier == @m")).mark_line().encode(
        x=alt.X('time:Q', title="Elapsed time (seconds)", axis=alt.Axis(labelAngle=0, tickCount=10)),
        y=alt.Y('mean(memory_usage_gib)', title="Total memory usage (GiB)"),
        color=alt.Color(
            'n_samples:N',
            legend=alt.Legend(
                title="Number of materials libraries",
                orient="top"
            )
        ),
        shape=alt.Shape('multiplier', legend=None),
        strokeDash=alt.StrokeDash('multiplier', legend=None)
    ).properties(title=f"Multiplier: {m}", width=1920, height=1080)
    for m in ['Original activity', '+50%', '+100%']
]

top = alt.hconcat(*charts[:3], spacing=20)
bottom = alt.hconcat(
    alt.Chart().mark_text(text='').properties(width=125),
    *charts[3:],
    alt.Chart().mark_text(text='').properties(width=125) 
)

title = alt.TitleParams(
    text="Materialization memory usage (GiB) (SQL database + RMLMapper and RMLStreamer mapping jobs) (Avg. across all tests)",
    offset=100,
    anchor='middle',
    fontSize=64
)
chart = alt.vconcat(top, bottom, spacing=40, title=title)

chart.save('materialization_memory_usage.pdf')

# Query benchmark results (w/ avgs)

In [28]:
query_benchmark_results_normal = query_benchmark_results[(query_benchmark_results["n_samples"] == 299) & (query_benchmark_results["multiplier"] == "Original activity")]
query_benchmark_results_extreme = query_benchmark_results[(query_benchmark_results["n_samples"] == 10000) & (query_benchmark_results["multiplier"] == "+100%")]

Avg across repetitions

In [29]:
query_benchmark_results_normal = query_benchmark_results_normal.groupby(['n_samples', 'multiplier', 'query', 'category', 'type'], as_index=False)['time'].mean()
query_benchmark_results_extreme = query_benchmark_results_extreme.groupby(['n_samples', 'multiplier', 'query', 'category', 'type'], as_index=False)['time'].mean()

In [30]:
def compute_winners(df):
    pivoted = df.pivot(index=['category', 'multiplier', 'query'], columns='type', values=['time']).reset_index()
    pivoted.columns = ['category', 'multiplier', 'query', 'time_sparql', 'time_sql']
    
    pivoted['sql_win'] = pivoted['time_sql'] < pivoted['time_sparql']
    pivoted['sparql_win'] = pivoted['time_sparql'] < pivoted['time_sql']
    
    sql_rows = pivoted[['category', 'multiplier', 'time_sql', 'sql_win']].rename(
        columns={'time_sql': 'time', 'sql_win': 'win'}
    )
    sql_rows['type'] = 'SQL'
    
    sparql_rows = pivoted[['category', 'multiplier', 'time_sparql', 'sparql_win']].rename(
        columns={'time_sparql': 'time', 'sparql_win': 'win'}
    )
    sparql_rows['type'] = 'SPARQL'
    
    df_with_winners = pd.concat([sql_rows, sparql_rows], ignore_index=True)
    return df_with_winners

query_benchmark_results_extreme = compute_winners(query_benchmark_results_extreme)
query_benchmark_results_normal = compute_winners(query_benchmark_results_normal)

x_label_order = ["Research objects", "Measurements", "Compositions", "Handovers", "Users"]

In [31]:
charts_avg = []
for df, title in [(query_benchmark_results_normal, "Original activity, 299 materials libraries"), (query_benchmark_results_extreme, "Increased activity (+100%), 10,000 materials libraries")]:
    base = alt.Chart(df).properties(width=600, height=550, title=title).encode(
        x=alt.X('category:N', title='Category', axis=alt.Axis(labelAngle=-45,  labelLimit=0, titlePadding=45), sort=x_label_order),
        color=alt.Color('type:N', scale=alt.Scale(domain=['SPARQL', 'SQL']), title='Datastore', legend=alt.Legend(title="Datastore", orient="top")),
        xOffset=alt.XOffset('type:N'),
        
    ).properties(
        width=1000, # For the paper: 800
        height=700 # For the paper: 600
    )

    # Compute mean and stdev per category/type
    agg = base.transform_aggregate(
        mean_time='mean(time)',
        stdev_time='stdev(time)',
        groupby=['category', 'type']
    ).transform_calculate(
        lower='max(0, datum.mean_time - datum.stdev_time)',
        upper='datum.mean_time + datum.stdev_time'
    )

    bars = agg.mark_bar(size=45).encode(
        y=alt.Y('mean_time:Q', title='Time (seconds)')
    )
    
    error_bars = agg.mark_errorbar(ticks=True, size=10, color='black').encode(
        y=alt.Y('lower:Q', title='Time (seconds)'),
        y2='upper:Q'
    )
    
    text = agg.mark_text(
        align='center',
        baseline='bottom',
        fontWeight='bold',
        dy=-2
    ).encode(
        y=alt.Y('mean_time:Q', title='Time (seconds)'),
        text=alt.Text('mean_time:Q', format='.2f')
    )


    charts_avg.append(bars + text + error_bars)

sparql_sql_benchmark_avgs = alt.hconcat(*charts_avg).resolve_scale(y='independent')
sparql_sql_benchmark_avgs.save('sparql_sql_benchmark_avg.pdf')

# ESWC 2026 poster figure

In [32]:
per_mapping_times_w_sums_eswc_2026 = per_mapping_times_w_sums.copy()
per_mapping_times_w_sums_eswc_2026['category'] = per_mapping_times_w_sums_eswc_2026['category'].replace("Compositions", "Chem. compositions")
per_mapping_times_w_sums_eswc_2026['category'] = per_mapping_times_w_sums_eswc_2026['category'].replace("Research objects", "Research objects")

In [33]:
mat_times_per_cat_charts = []

x_axis_values = list(range(0, per_mapping_times_w_sums_eswc_2026['n_samples'].max() + 1000, 1000))

indexes_with_y_axis = [0] 

for i, m in enumerate(['Original activity', '+50%', '+100%']):
    if i in indexes_with_y_axis:
        bar_y_axis = alt.Y('mean(real_time_max_for_category):Q', 
                           title="SQL querying time (seconds)", 
                           axis=alt.Axis(tickCount=10), 
                           scale=alt.Scale(type='log', base=2))
        # Move the title up or down depending on the plot. I could not find another way...
        title_dy = 0
    else:
        y_axis_config = alt.Axis(labels=False, title=None, ticks=False, domain=False, tickCount=10)
        bar_y_axis = alt.Y('mean(real_time_max_for_category):Q', 
                           axis=y_axis_config, 
                           scale=alt.Scale(type='log', base=2))
        title_dy = -15

    # X-axis title only for the middle chart
    x_title = "Number of materials libraries" if i == 1 else None
    
    base_layer = alt.Chart(per_mapping_times_w_sums_eswc_2026.query("multiplier == @m")).encode(
        x=alt.X('n_samples:Q', 
                title=x_title,
                axis=alt.Axis(values=x_axis_values, labelAngle=-45)),
        y=bar_y_axis,
        color=alt.Color('category:N', 
                        legend=alt.Legend(title="Mapping category", orient="bottom"))
    )

    line_layer = base_layer.mark_line(size=8)
    point_layer = base_layer.mark_point(size=600, filled=True)

    error_chart = alt.Chart(per_mapping_times_w_sums_eswc_2026.query("multiplier == @m")).transform_calculate(
        log_val='log(datum.real_time_max_for_category)/log(2)'
    ).transform_aggregate(
        mean_log='mean(log_val)',
        sd_log='stdev(log_val)',
        groupby=['category', 'n_samples']
    ).transform_calculate(
        upper_log='datum.mean_log + datum.sd_log',
        lower_log='datum.mean_log - datum.sd_log',
        upper='pow(2, datum.upper_log)',
        lower='pow(2, datum.lower_log)'
    ).mark_rule(strokeWidth=4).encode(
        x=alt.X('n_samples:Q'),
        y=alt.Y('lower:Q', scale=alt.Scale(type='log', base=2)),
        y2='upper:Q',
        color=alt.Color('category:N', legend=None)
    )
    
    combined = (line_layer + point_layer + error_chart).properties(
        title=alt.TitleParams(
            text=f"Increased activity modifier: {m}" if i > 0 else "Original activity",
            dy=title_dy
        ),
        width=625, 
        height=550
    )
    
    mat_times_per_cat_charts.append(combined)

mat_times_per_category_chart = alt.hconcat(*mat_times_per_cat_charts, spacing=20).resolve_scale(y='shared')

In [34]:
query_benchmark_results_normal_eswc_2026 = query_benchmark_results_normal.copy()
query_benchmark_results_normal_eswc_2026['category'] = query_benchmark_results_normal_eswc_2026['category'].replace("Compositions", "Chem. comp.")
query_benchmark_results_normal_eswc_2026['category'] = query_benchmark_results_normal_eswc_2026['category'].replace("Research objects", "Research objects")

In [35]:
charts_avg = []
for df, title in [(query_benchmark_results_normal_eswc_2026, "Original activity, 299 materials libraries"), (query_benchmark_results_extreme, "Increased activity (+100%), 10,000 materials libraries")]:
    base = alt.Chart(df).properties(width=600, height=550, title=title).encode(
        x=alt.X('category:N', title='Category', axis=alt.Axis(labelAngle=-45,  labelLimit=0, titlePadding=45), sort=x_label_order),
        color=alt.Color('type:N', scale=alt.Scale(domain=['SPARQL', 'SQL']), title='Datastore', legend=alt.Legend(title="Datastore", orient="bottom")),
        xOffset=alt.XOffset('type:N'),
        
    ).properties(
        width=1000, # For the paper: 800
        height=700 # For the paper: 600
    )

    # Compute mean and stdev per category/type
    agg = base.transform_aggregate(
        mean_time='mean(time)',
        stdev_time='stdev(time)',
        groupby=['category', 'type']
    ).transform_calculate(
        lower='max(0, datum.mean_time - datum.stdev_time)',
        upper='datum.mean_time + datum.stdev_time'
    )

    bars = agg.mark_bar(size=45).encode(
        y=alt.Y('mean_time:Q', title='Time (seconds)')
    )
    
    error_bars = agg.mark_errorbar(ticks=True, size=10, color='black', thickness=4).encode(
        y=alt.Y('lower:Q', title='Time (seconds)'),
        y2='upper:Q'
    )
    
    text = agg.mark_text(
        align='center',
        baseline='bottom',
        fontWeight='bold',
        dy=-2
    ).encode(
        y=alt.Y('mean_time:Q', title='Time (seconds)'),
        text=alt.Text('mean_time:Q', format='.2f')
    )


    charts_avg.append(bars + text + error_bars)

In [36]:
alt.theme.enable('theme_color_scheme_2_larger_fontsize')
shared_width = 1200
shared_height = 1000

eswc_2026_poster_plot = alt.hconcat(
    mat_times_per_cat_charts[0].properties(
        width=shared_width, 
        height=shared_height,
        title=["SQL querying times", "per no. of research objects and data category"]
    ), 
    charts_avg[0].properties(
        width=shared_width, 
        height=shared_height,
        title=["SPARQL vs. SQL query performance",  "per data category"]
    ),
    spacing=250
).resolve_scale(
    color='independent',
    y='independent',
    x='independent'
).configure_axisY(
    tickCount=5 
).configure_legend(
    symbolSize=1000,      
)

eswc_2026_poster_plot.save('eswc_2026_poster_plot.pdf')

In [37]:
alt.theme.enable('theme_color_scheme_2')

ThemeRegistry.enable('theme_color_scheme_2')

# Query benchmark results (w/o avgs)

In [38]:
query_benchmark_results_normal = query_benchmark_results[(query_benchmark_results["n_samples"] == 299) & (query_benchmark_results["multiplier"] == "Original activity")]
query_benchmark_results_extreme = query_benchmark_results[(query_benchmark_results["n_samples"] == 10000) & (query_benchmark_results["multiplier"] == "+100%")]

Avg. across repetitions

In [39]:
query_benchmark_results_normal = query_benchmark_results_normal.groupby(['n_samples', 'multiplier', 'query', 'category', 'type'], as_index=False)['time'].mean()
query_benchmark_results_extreme = query_benchmark_results_extreme.groupby(['n_samples', 'multiplier', 'query', 'category', 'type'], as_index=False)['time'].mean()

In [40]:
def compute_winners_no_avgs(df):
    pivoted = df.pivot(index=['category', 'multiplier', 'query'], columns='type', values=['time']).reset_index()
    pivoted.columns = ['category', 'multiplier', 'query', 'time_sparql', 'time_sql']
    
    pivoted['sql_win'] = pivoted['time_sql'] < pivoted['time_sparql']
    pivoted['sparql_win'] = pivoted['time_sparql'] < pivoted['time_sql']
    
    sql_rows = pivoted[['category', 'multiplier', 'query', 'time_sql', 'sql_win']].rename(
        columns={'time_sql': 'time', 'sql_win': 'win'}
    )
    sql_rows['type'] = 'SQL'
    
    sparql_rows = pivoted[['category', 'multiplier', 'query', 'time_sparql', 'sparql_win']].rename(
        columns={'time_sparql': 'time', 'sparql_win': 'win'}
    )
    sparql_rows['type'] = 'SPARQL'
    
    df_with_winners = pd.concat([sql_rows, sparql_rows], ignore_index=True)
    return df_with_winners

query_benchmark_results_extreme = compute_winners_no_avgs(query_benchmark_results_extreme)
query_benchmark_results_normal = compute_winners_no_avgs(query_benchmark_results_normal)

In [41]:
from textwrap import wrap

rename_map = {
    'samples_with_specific_elements': 'Materials libraries of silver or gold',
    'samples_with_specific_elements_exclusive': 'Materials libraries of silver and gold',
    'samples_and_authors': 'Materials libraries and creators',
    'samples_not_composed_of_elements': 'Materials libraries not of silver or gold',
    'samples_with_substrates': 'Substrate of every materials library',

    'get_edx_csv_measurements': 'All EDX measurements',
    'measurements_and_authors': 'Measurements and creators',
    
    'composition_count_per_MA': 'Measurement area compositions counts',
    'query_based_on_composition_values': 'Gold composition values',
    
    
    'handovers_with_specific_measurement_type': 'Handovers with XRD measurements',
    'measurement_to_handovers': 'Measurements to handover correspondences',
    
    'query_user_details': 'All user details',
    'samples_per_user': 'Materials libraries authored per user'
}

query_benchmark_results_normal['query'] = query_benchmark_results_normal['query'].replace(rename_map)
query_benchmark_results_extreme['query'] = query_benchmark_results_extreme['query'].replace(rename_map)

x_label_order = list(rename_map.values())

In [42]:
charts_no_avg = []
for df, title in [(query_benchmark_results_normal, "Original activity, 299 materials libraries"), (query_benchmark_results_extreme, "Increased activity (+100%), 10,000 materials libraries")]:
    base = alt.Chart(df).properties(width=600, height=550, title=title).encode(
        x=alt.X('query:N', title='Query', axis=alt.Axis(labelAngle=-45, labelLimit=0, titlePadding=125), sort=x_label_order),
        y=alt.Y('time:Q', title='Time (seconds)'),
        color=alt.Color('type:N', scale=alt.Scale(domain=['SPARQL', 'SQL']), title='Datastore'),
        xOffset=alt.XOffset('type:N')
    ).mark_bar(size=15).properties(width=1920, height=1080)
    
    text = base.mark_text(
        align='center',
        baseline='bottom',
        fontSize=12,
        fontWeight='bold',
        dy=-2
    ).encode(
        y=alt.Y('time:Q', title='Time (seconds)'),
        text=alt.Text('time:Q', format='.3f')
    )

    charts_no_avg.append(base + text)

sparql_sql_benchmark_no_avgs = alt.hconcat(*charts_no_avg).resolve_scale(y='independent')
sparql_sql_benchmark_no_avgs.save('sparql_sql_benchmark_no_avg.pdf')

# Query benchmark stats

## General

In [43]:
query_benchmark_results[query_benchmark_results["type"] == "sql"]["time"].mean()

np.float64(7.837389401826335)

In [44]:
query_benchmark_results[query_benchmark_results["type"] == "sql"]["time"].std()

np.float64(50.353095152501886)

In [45]:
query_benchmark_results[query_benchmark_results["type"] == "sparql"]["time"].mean()

np.float64(0.1450377557708633)

In [46]:
query_benchmark_results[query_benchmark_results["type"] == "sparql"]["time"].std()

np.float64(0.3733367483040336)

## Samples, measurements and users

In [47]:
def get_difference(sql_times, sparql_times):
    n_sql = len(sql_times)
    n_sparql = len(sparql_times)

    mean_sql = sql_times.mean()        
    mean_sparql = sparql_times.mean()  
    std_sql = sql_times.std()           
    std_sparql = sparql_times.std() 
    
    sem_sql = std_sql / np.sqrt(n_sql)
    sem_sparql = std_sparql / np.sqrt(n_sparql)
        
    diff_mean = mean_sql - mean_sparql
    diff_sem = np.sqrt(sem_sql**2 + sem_sparql**2)
    
    percent_improvement = (diff_mean / mean_sql) * 100

    print(f"SQL mean: {mean_sql}")
    print(f"SQL stdev: {std_sql}")
    print(f"SPARQL mean: {mean_sparql}")
    print(f"SPARQL stdev: {std_sparql}")
    print(f"Difference in means: {diff_mean:.4f}")
    print(f"Propagated Standard Error: {diff_sem:.4f}")
    print(f"SEM: {diff_mean:.3f} +- {diff_sem:.3f}")
    print(f"SPARQL Improvement: {percent_improvement:.2f}% faster than SQL")

## ESWC 2026 stats

***Avg. difference in the production DB (March 2026)***

In the production DB we only have a difference of a few milliseconds for data intensive queries. The results will vary slightly as there are were repetitions of the same tests added after submission (e.g. 99.16% improvement in  handover workflows to 99.97% now).

### Avg. difference in production

In [48]:
query_benchmark_results_prod = list(json.load(open('iswc_performance_test_prod.json'))[0]["query_benchmark_results"].items())

rows = []
for name, times in query_benchmark_results_prod:
    rows.append({'query': name, 'category': query_categories[name], 'type': 'SQL', 'time': times[0]})
    rows.append({'query': name, 'category': query_categories[name], 'type': 'SPARQL', 'time': times[1]})

query_benchmark_results_prod = pd.DataFrame(rows)

sql = query_benchmark_results_prod[(query_benchmark_results_prod["type"] == "SQL")]["time"]
sparql = query_benchmark_results_prod[(query_benchmark_results_prod["type"] == "SPARQL")]["time"]

get_difference(sql, sparql)

SQL mean: 0.016513665761941902
SQL stdev: 0.0011607550238672138
SPARQL mean: 0.025022806375860594
SPARQL stdev: 0.01386646271826811
Difference in means: -0.0085
Propagated Standard Error: 0.0039
SEM: -0.009 +- 0.004
SPARQL Improvement: -51.53% faster than SQL

In [49]:
prod_handovers_sql = query_benchmark_results_prod[
    (query_benchmark_results_prod["type"] == "SQL") & 
    (query_benchmark_results_prod["category"].isin(["Handovers"]))
]["time"]

prod_handovers_sparql = query_benchmark_results_prod[
    (query_benchmark_results_prod["type"] == "SPARQL") & 
    (query_benchmark_results_prod["category"].isin(["Handovers"]))
]["time"]

get_difference(prod_handovers_sql, prod_handovers_sparql)

SQL mean: 0.016925362579058856
SQL stdev: 0.0009141087563277955
SPARQL mean: 0.02515368052991107
SPARQL stdev: 0.01094518777664414
Difference in means: -0.0082
Propagated Standard Error: 0.0078
SEM: -0.008 +- 0.008
SPARQL Improvement: -48.62% faster than SQL

### Avg. difference in the real distribution of data

In [50]:
sql = query_benchmark_results_normal[(query_benchmark_results_normal["type"] == "SQL")]["time"]
sparql = query_benchmark_results_normal[(query_benchmark_results_normal["type"] == "SPARQL")]["time"]

get_difference(sql, sparql)

SQL mean: 0.11529726617468093
SQL stdev: 0.04405313955707896
SPARQL mean: 0.031969691722247846
SPARQL stdev: 0.022517144151203247
Difference in means: 0.0833
Propagated Standard Error: 0.0137
SEM: 0.083 +- 0.014
SPARQL Improvement: 72.27% faster than SQL

### Avg. difference in synthetic DB

In [51]:
sql = query_benchmark_results_extreme[(query_benchmark_results_extreme["type"] == "SQL")]["time"]
sparql = query_benchmark_results_extreme[(query_benchmark_results_extreme["type"] == "SPARQL")]["time"]

get_difference(sql, sparql)

SQL mean: 49.261882111086145
SQL stdev: 154.58463378432228
SPARQL mean: 0.3849835730059288
SPARQL stdev: 0.8539604006382279
Difference in means: 48.8769
Propagated Standard Error: 42.8747
SEM: 48.877 +- 42.875
SPARQL Improvement: 99.22% faster than SQL

***Avg. difference in the largest db for handovers and compositions***

In [52]:
extreme_handovers_sql = query_benchmark_results_extreme[
    (query_benchmark_results_extreme["type"] == "SQL") & 
    (query_benchmark_results_extreme["category"].isin(["Handovers"]))
]["time"]

extreme_handovers_sparql = query_benchmark_results_extreme[
    (query_benchmark_results_extreme["type"] == "SPARQL") & 
    (query_benchmark_results_extreme["category"].isin(["Handovers"]))
]["time"]

get_difference(extreme_handovers_sql, extreme_handovers_sparql)

SQL mean: 306.99707243416435
SQL stdev: 359.6383791843057
SPARQL mean: 0.10130754899485812
SPARQL stdev: 0.04617640671179977
Difference in means: 306.8958
Propagated Standard Error: 254.3027
SEM: 306.896 +- 254.303
SPARQL Improvement: 99.97% faster than SQL

In [53]:
extreme_handovers_sql = query_benchmark_results_extreme[
    (query_benchmark_results_extreme["type"] == "SQL") & 
    (query_benchmark_results_extreme["category"].isin(["Compositions"]))
]["time"]

extreme_handovers_sparql = query_benchmark_results_extreme[
    (query_benchmark_results_extreme["type"] == "SPARQL") & 
    (query_benchmark_results_extreme["category"].isin(["Compositions"]))
]["time"]

get_difference(extreme_handovers_sql, extreme_handovers_sparql)

SQL mean: 11.801378673670115
SQL stdev: 13.808285847018809
SPARQL mean: 1.5413699532994847
SPARQL stdev: 2.1572470366902037
Difference in means: 10.2600
Propagated Standard Error: 9.8824
SEM: 10.260 +- 9.882
SPARQL Improvement: 86.94% faster than SQL